---
Name: socialfeed
---
SilverStripe\CMS\Controllers\ContentController:
  extensions:
    - IsaacRankin\SocialFeed\SocialFeedControllerExtension
SilverStripe\Core\Injector\Injector:
  Psr\SimpleCache\CacheInterface.SocialFeedProvider:
    factory: SilverStripe\Core\Cache\CacheFactory
    constructor:
      namespace: "SocialFeedProvider"
      defaultLifetime: 900
